services:
  postgresql:
    container_name: postgresql
    image: postgres:17.6
    volumes:
    - psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"
    restart: no

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis-data:/var/lib/redis
    restart: no
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.4-management
    volumes:
      - rabbit-data:/var/lib/rabbitmq/
    environment:
      RABBITMQ_HOST: '%'
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: no

  flower:
   image: mher/flower:latest
   container_name: flower
   command: celery flower --port=5555 --basic_auth=guest:guest
   environment:
     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
     - FLOWER_PORT=5555
   ports:
   - "5555:5555"
   volumes:
   - flower-data:/data


volumes:
  psql-data:
    driver: local
  flower-data:
    driver: local
  redis-data:
    driver: local
  rabbit-data:
    driver: local
