default:
  DEBUG: true
  SECRET_KEY: django-insecure-y#+010ocsw+-x-1**lb%xza+o4k4p#sxojlw29@utyv)2j)as%
  ALLOWED_HOSTS: [ ]
  AUTH_USER_MODEL: actors.User
  INSTALLED_APPS:
    - django.contrib.admin
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.messages
    - django.contrib.staticfiles
    - django_filters
    - rest_framework
    - drf_spectacular
    - django_celery_beat
    - django_celery_results

    - actors
  MIDDLEWARE:
    - django.middleware.security.SecurityMiddleware
    - django.contrib.sessions.middleware.SessionMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.contrib.auth.middleware.AuthenticationMiddleware
    - django.contrib.messages.middleware.MessageMiddleware
    - django.middleware.clickjacking.XFrameOptionsMiddleware
  ROOT_URLCONF: svango.urls
  TEMPLATES:
    - BACKEND: django.template.backends.django.DjangoTemplates
      DIRS: [ ]
      APP_DIRS: true
      OPTIONS:
        context_processors:
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
          - django.contrib.messages.context_processors.messages
  WSGI_APPLICATION: svango.wsgi.application
  CACHES:
    default:
      BACKEND: django.core.cache.backends.redis.RedisCache
      LOCATION: redis://127.0.0.1:6379
      OPTIONS:
        db: 0
    celery:
      BACKEND: django.core.cache.backends.redis.RedisCache
      LOCATION: redis://127.0.0.1:6379
      OPTIONS:
        db: 1
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      NAME: django_db
      USER: django_user
      PASSWORD: django
      HOST: 127.0.0.1
      PORT: 5432
  AUTH_PASSWORD_VALIDATORS:
    - NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
    - NAME: django.contrib.auth.password_validation.MinimumLengthValidator
    - NAME: django.contrib.auth.password_validation.CommonPasswordValidator
    - NAME: django.contrib.auth.password_validation.NumericPasswordValidator
  LANGUAGE_CODE: en-us
  USE_I18N: true
  USE_TZ: true
  STATIC_ROOT: static
  STATIC_URL: /static/
  MEDIA_URL: /media/
  MEDIA_ROOT: static/media
  DEFAULT_AUTO_FIELD: django.db.models.BigAutoField
  REST_FRAMEWORK:
    DEFAULT_AUTHENTICATION_CLASSES:
      - rest_framework_simplejwt.authentication.JWTAuthentication
    DEFAULT_PERMISSION_CLASSES:
      - rest_framework.permissions.IsAuthenticated
      - common.utils.permissions.DjangoModelCrudPermissions
    DEFAULT_FILTER_BACKENDS:
      - django_filters.rest_framework.backends.DjangoFilterBackend
      - rest_framework.filters.SearchFilter
      - rest_framework.filters.OrderingFilter
    DEFAULT_SCHEMA_CLASS: drf_spectacular.openapi.AutoSchema
    DEFAULT_PAGINATION_CLASS: rest_framework.pagination.LimitOffsetPagination
    PAGE_SIZE: 10
  SIMPLE_JWT:
    TOKEN_OBTAIN_SERIALIZER: rest_framework_simplejwt.serializers.TokenObtainPairSerializer
  SPECTACULAR_SETTINGS:
    TITLE: svango
    DESCRIPTION: django drf jwt dynaconf swagger pytest template
    VERSION: '@format {this.VERSION}'
    COMPONENT_SPLIT_REQUEST: True
  AUTH_LDAP_SERVER_URI: 'ldap://ldap.host'
  AUTH_LDAP_BIND_DN: 'cn=testcn,ou=test_users,dc=testdc'
  AUTH_LDAP_BIND_PASSWORD: 'some_pass'
  AUTH_LDAP_USER_SEARCH_PARAMS:
    base_dn: ou=users,dc=test
    scope: 2
    filterstr: (objectClass=*)
    attrlist: [ ]
  AUTH_LDAP_USER_ATTR_MAP:
    first_name: givenName
    last_name: sn
    email: mail
    username: sAMAccountName
    phone: mobile
  CELERY_TIMEZONE: UTC
  CELERY_RESULT_BACKEND: svango.celery_backend.SvangoCacheBackend
  CELERY_CACHE_BACKEND: celery
  CELERY_TASK_TRACK_STARTED: true
  CELERY_RESULT_EXTENDED: true

development:
  DEBUG: true
  REST_FRAMEWORK:
    dynaconf_merge: true
    DEFAULT_AUTHENTICATION_CLASSES:
      - rest_framework.authentication.SessionAuthentication

production:
  DEBUG: false

testing:
  DEBUG: true
  ALLOWED_HOSTS:
    - testserver
  TEMPLATE_DEBUG: false
  PASSWORD_HASHERS:
    - django.contrib.auth.hashers.MD5PasswordHasher
  MEDIA_ROOT: /tmp
  REST_FRAMEWORK:
    dynaconf_merge: true
    DEFAULT_AUTHENTICATION_CLASSES:
      - rest_framework.authentication.SessionAuthentication
  CACHES:
    default:
      BACKEND: django.core.cache.backends.locmem.LocMemCache
  CELERY_TASK_ALWAYS_EAGER: true
  CELERY_CACHE_BACKEND: default
