"""Django settings for svango project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import datetime
import subprocess
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
VERSION = subprocess.run(['poetry', 'version'], check=False, capture_output=True, text=True).stdout.strip()  # noqa: S607
AUTH_LDAP_USER_SEARCH = None

# HERE STARTS DYNACONF EXTENSION LOAD (Keep at the very bottom of settings.py)
# Read more at https://www.dynaconf.com/django/
import dynaconf  # noqa: E402


def converters_setup() -> None:
    dynaconf.add_converter('path', Path)
    dynaconf.add_converter('timedelta', lambda e: datetime.timedelta(float(e)))
    dynaconf.add_converter('bytes', lambda e: e.encode('utf-8'))


settings = dynaconf.DjangoDynaconf(__name__, post_hooks=converters_setup)
settings.setenv()
# HERE ENDS DYNACONF EXTENSION LOAD (No more code below this line)
