services:

  svango:
    container_name: svango
    image: svango:prod
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    entrypoint:
      - /app/docker/entrypoints/run_svango.sh
    depends_on:
      - postgresql
      - rabbitmq
      - redis
    env_file: ./env
    tty: true
    volumes:
      - static-files:/app/staticfiles
    ports:
      - "81:8000"
    restart: always

  asgi:
    container_name: asgi
    image: svango:prod
    entrypoint:
      - /app/docker/entrypoints/run_asgi.sh
    volumes:
      - static-files:/app/staticfiles
    env_file: ./env
    ports:
      - 8001:8001
    restart: always

  postgresql:
    container_name: postgresql
    image: postgres:17.6
    volumes:
    - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"
    restart: no

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis-data:/var/lib/redis
    restart: no
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.4-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
    environment:
      RABBITMQ_HOST: '%'
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: no

  celery:
    container_name: celery
    image: svango:prod
    entrypoint:
      - /app/docker/entrypoints/run_celery.sh
    depends_on:
      - postgresql
      - rabbitmq
      - redis
    env_file: ./env
    tty: true
    volumes:
      - static-files:/app/staticfiles
    restart: always

  beat:
    container_name: beat
    image: svango:prod
    entrypoint:
      - /app/docker/entrypoints/run_celery_beat.sh
    depends_on:
      - postgresql
      - rabbitmq
      - redis
    env_file: ./env
    tty: true
    volumes:
      - static-files:/app/staticfiles
    restart: always

  flower:
   image: mher/flower:latest
   container_name: flower
   command: celery flower --port=5555 --basic_auth=guest:guest
   environment:
     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
     - FLOWER_PORT=5555
   ports:
   - "5555:5555"
   volumes:
   - flower-data:/data


volumes:
  static-files:
    driver: local
  postgresql-data:
    driver: local
  flower-data:
    driver: local
  redis-data:
    driver: local
  rabbitmq-data:
    driver: local
