# Generated by Django 5.2.1 on 2025-07-07 09:21

import actors.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group_permissions',),
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', actors.managers.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('actors.user_groups',),
            managers=[
                ('objects', actors.managers.UserGroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', actors.managers.UserPermissionManager()),
            ],
        ),
    ]
