# Generated by Django 5.2.4 on 2025-10-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_grouppermission_permissiongroup_usergroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
